//! Flow architecture S5 gate, leg 1: N-peer STRUCTURAL convergence fuzz.
//! Random adds/deletes/moves/strikes/renames/annotations race across peers
//! with randomized pairwise sync rounds; after every full mesh sync all
//! boards must be byte-identical, pass the validator, AND equal a fresh
//! from-snapshot materialization (materializer equivalence).
//!
//! Default rounds keep CI fast; `FLOWSTATE_FLOW_FUZZ_ROUNDS` scales to the
//! 10k+ soak.
#[cfg(test)]
mod tests {
  use flowstate_collab::flow::{FlowDocHandle, FlowPublishEvent, FlowRuntime};
  use flowstate_collab::local_write::GateHolder;
  use flowstate_document::{InputParagraph, InputRun, RunStyles};
  use flowstate_flow::{
    AnnotationOriginator, AnnotationStroke, BoardPoint, BoardRect, CellId, CellPlacement, CellSeed, FlowDropIntent, FlowIntent, SheetId,
    StrokeStyle,
  };
  use uuid::Uuid;

  struct Rng(u64);
  impl Rng {
    fn next(&mut self) -> u64 {
      self.0 ^= self.0 << 13;
      self.0 ^= self.0 >> 7;
      self.0 ^= self.0 << 17;
      self.0
    }
    fn below(&mut self, bound: usize) -> usize {
      (self.next() % bound.max(1) as u64) as usize
    }

    /// Deterministic uuid so failures replay exactly.
    fn uuid(&mut self) -> Uuid {
      Uuid::from_u128((u128::from(self.next()) << 64) | u128::from(self.next()))
    }
  }

  /// Compact, reviewable divergence report: per-sheet cell tuples.
  fn board_signature(board: &flowstate_flow::FlowBoardProjection) -> Vec<String> {
    let mut lines = Vec::new();
    for sheet in &board.sheets {
      lines.push(format!("sheet {} name={:?} cells={}", sheet.id, sheet.name, sheet.cells.len()));
      for cell in &sheet.cells {
        lines.push(format!(
          "  cell {} col={} parent={:?} struck={} empty={} summary={:?}",
          cell.id, cell.column_id, cell.parent_id, cell.summary.struck, cell.summary.is_empty, cell.summary.summary_text
        ));
      }
      lines.push(format!("  annotations={}", sheet.annotations.len()));
    }
    lines
  }

  #[track_caller]
  fn assert_boards_equal(reference: &flowstate_flow::FlowBoardProjection, other: &flowstate_flow::FlowBoardProjection, label: &str) {
    if reference == other {
      return;
    }
    let ours = board_signature(reference);
    let theirs = board_signature(other);
    use std::fmt::Write as _;
    let mut diff = String::new();
    for i in 0..ours.len().max(theirs.len()) {
      let a = ours.get(i).map_or("<absent>", String::as_str);
      let b = theirs.get(i).map_or("<absent>", String::as_str);
      if a != b {
        let _ = writeln!(diff, "- {a}\n+ {b}");
      }
    }
    if diff.is_empty() {
      diff = "signatures equal; divergence is in a field the signature omits".into();
    }
    panic!("{label}: boards diverged:\n{diff}");
  }

  fn paragraphs(text: &str) -> Vec<InputParagraph> {
    vec![InputParagraph {
      style: flowstate_document::PARAGRAPH_TAG,
      runs: vec![InputRun {
        text: text.into(),
        styles: RunStyles::default(),
      }],
    }]
  }

  fn drain_updates(handle: &FlowDocHandle) -> Vec<Vec<u8>> {
    let mut guard = handle.gate().lock(GateHolder::DocumentService).unwrap();
    guard
      .take_pending_publish()
      .into_iter()
      .map(|FlowPublishEvent::LocalUpdate { bytes, .. }| bytes)
      .collect()
  }

  fn full_mesh_sync(peers: &[FlowDocHandle]) {
    // Exchange rounds until quiescent (bounded): every publish reaches every
    // peer, including updates generated by imports (none today, but cheap).
    for _ in 0..4 {
      let batches: Vec<Vec<Vec<u8>>> = peers.iter().map(drain_updates).collect();
      let mut any = false;
      for (source, updates) in batches.iter().enumerate() {
        if updates.is_empty() {
          continue;
        }
        any = true;
        for (target, peer) in peers.iter().enumerate() {
          if target == source {
            continue;
          }
          peer
            .import_remote_updates(&updates.iter().map(Vec::as_slice).collect::<Vec<_>>())
            .unwrap();
        }
      }
      if !any {
        break;
      }
    }
  }

  fn live_cells(handle: &FlowDocHandle, sheet: SheetId) -> Vec<CellId> {
    handle
      .board_projection()
      .unwrap()
      .sheet(sheet)
      .map(|sheet| sheet.cells.iter().map(|cell| cell.id).collect())
      .unwrap_or_default()
  }

  #[test]
  fn n_peer_structural_convergence() {
    let rounds: usize = std::env::var("FLOWSTATE_FLOW_FUZZ_ROUNDS")
      .ok()
      .and_then(|value| value.parse().ok())
      .unwrap_or(60);
    let mut rng = Rng(0xf10c_5eed_0001);

    let seed_runtime = FlowRuntime::new_empty();
    let sheet_type = seed_runtime.board().format.sheet_types[0].id;
    let (seed_handle, _gate) = FlowDocHandle::new(seed_runtime);
    let sheet = rng.uuid();
    seed_handle
      .apply(&FlowIntent::CreateSheet {
        sheet_id: sheet,
        name: "Fuzz".into(),
        sheet_type_id: sheet_type,
      })
      .unwrap();
    let snapshot = {
      let guard = seed_handle
        .gate()
        .lock(GateHolder::DocumentService)
        .unwrap();
      guard.snapshot_bytes().unwrap()
    };
    let peers: Vec<FlowDocHandle> = (0..3)
      .map(|_| FlowDocHandle::new(FlowRuntime::from_snapshot(&snapshot).unwrap()).0)
      .collect();

    let mut minted = 0_usize;
    for round in 0..rounds {
      for (peer_ix, peer) in peers.iter().enumerate() {
        let ops = 1 + rng.below(3);
        for _ in 0..ops {
          let cells = live_cells(peer, sheet);
          let roll = rng.below(8);
          let result: Result<(), String> = match roll {
            0 | 1 => {
              let cell_id = rng.uuid();
              let placement = if cells.is_empty() || rng.below(3) == 0 {
                CellPlacement::SheetEnd { column_index: rng.below(3) }
              } else {
                CellPlacement::After(cells[rng.below(cells.len())])
              };
              minted += 1;
              peer
                .apply(&FlowIntent::AddCell {
                  sheet_id: sheet,
                  cell_id,
                  placement,
                  seed: CellSeed::Paragraphs(paragraphs(&format!("r{round} p{peer_ix} c{minted}"))),
                })
                .map(|_| ())
                .map_err(|error| error.to_string())
            },
            2 if !cells.is_empty() => {
              let parent = cells[rng.below(cells.len())];
              peer
                .apply(&FlowIntent::AddCell {
                  sheet_id: sheet,
                  cell_id: rng.uuid(),
                  placement: CellPlacement::LastChildOf(parent),
                  seed: CellSeed::Empty,
                })
                .map(|_| ())
                .map_err(|error| error.to_string())
            },
            3 if cells.len() > 2 => peer
              .apply(&FlowIntent::DeleteCell {
                sheet_id: sheet,
                cell_id: cells[rng.below(cells.len())],
              })
              .map(|_| ())
              .map_err(|error| error.to_string()),
            4 if cells.len() > 1 => {
              let mover = cells[rng.below(cells.len())];
              let target = cells[rng.below(cells.len())];
              let drop = match rng.below(4) {
                0 => FlowDropIntent::BeforeSibling(target),
                1 => FlowDropIntent::AfterSibling(target),
                2 => FlowDropIntent::LastChildOf(target),
                _ => FlowDropIntent::RootInColumn {
                  column_index: rng.below(3),
                  insertion_index: rng.below(cells.len() + 1),
                },
              };
              peer
                .apply(&FlowIntent::MoveCellSubtree {
                  sheet_id: sheet,
                  cell_id: mover,
                  drop,
                })
                .map(|_| ())
                .map_err(|error| error.to_string())
            },
            5 if !cells.is_empty() => peer
              .apply(&FlowIntent::SetCellStruck {
                sheet_id: sheet,
                cell_id: cells[rng.below(cells.len())],
                struck: rng.below(2) == 0,
              })
              .map(|_| ())
              .map_err(|error| error.to_string()),
            6 => peer
              .apply(&FlowIntent::AddAnnotation {
                stroke: AnnotationStroke {
                  id: rng.uuid(),
                  sheet_id: sheet,
                  originator: AnnotationOriginator(format!("peer-{peer_ix}")),
                  points: vec![BoardPoint {
                    x: rng.below(500) as f32,
                    y: rng.below(500) as f32,
                  }],
                  style: StrokeStyle {
                    color_rgba: 0xff33_3333,
                    width: 2.0,
                    opacity: 1.0,
                  },
                  bbox: BoardRect::default(),
                },
              })
              .map(|_| ())
              .map_err(|error| error.to_string()),
            _ => peer
              .apply(&FlowIntent::RenameSheet {
                sheet_id: sheet,
                name: format!("Fuzz r{round}"),
              })
              .map(|_| ())
              .map_err(|error| error.to_string()),
          };
          let _ = result; // refusals are legitimate under concurrency
        }
        // Occasional local undo keeps the undo stack in the mix.
        if rng.below(10) == 0 {
          let _ = peer.undo();
        }
      }

      full_mesh_sync(&peers);

      let reference = peers[0].board_projection().unwrap();
      reference
        .validate()
        .unwrap_or_else(|error| panic!("round {round}: normalized board failed validation: {error}"));
      for (peer_ix, peer) in peers.iter().enumerate().skip(1) {
        assert_eq!(reference, peer.board_projection().unwrap(), "round {round}: peer {peer_ix} diverged");
      }
      // Materializer equivalence: a cold open of the same canonical state must
      // produce the identical board.
      let snapshot = {
        let guard = peers[0].gate().lock(GateHolder::DocumentService).unwrap();
        guard.snapshot_bytes().unwrap()
      };
      let cold = FlowRuntime::from_snapshot(&snapshot).unwrap();
      assert_boards_equal(&reference, cold.board(), &format!("round {round}: cold rematerialization"));
    }
  }
}
