impl From<&DocumentTheme> for DocumentThemeSettings {
  fn from(theme: &DocumentTheme) -> Self {
    Self {
      default_font_family: theme.default_font_family.to_string(),
      default_text_color: theme.default_text_color.into(),
      document_background_color: theme.document_background_color.into(),
      pageless_inset_x: theme.pageless_inset_x.as_f32(),
      pageless_inset_top: theme.pageless_inset_top.as_f32(),
      pageless_inset_bottom: theme.pageless_inset_bottom.as_f32(),
      body_font_size: theme.body_font_size.as_f32(),
      cite_font_size: theme.cite_font_size.as_f32(),
      condensed_font_size: theme.condensed_font_size.as_f32(),
      ultracondensed_font_size: theme.ultracondensed_font_size.as_f32(),
      pocket_font_size: theme.pocket_font_size.as_f32(),
      hat_font_size: theme.hat_font_size.as_f32(),
      block_font_size: theme.block_font_size.as_f32(),
      tag_font_size: theme.tag_font_size.as_f32(),
      undertag_font_size: theme.undertag_font_size.as_f32(),
      line_spacing: theme.line_spacing,
      line_gap_fraction: theme.line_gap_fraction,
      paragraph_after: theme.paragraph_after.as_f32(),
      pocket_before: theme.pocket_before.as_f32(),
      hat_before: theme.hat_before.as_f32(),
      block_before: theme.block_before.as_f32(),
      tag_before: theme.tag_before.as_f32(),
      pocket_border_width: theme.pocket_border_width.as_f32(),
      pocket_border_space_x: theme.pocket_border_space_x.as_f32(),
      pocket_border_space_y: theme.pocket_border_space_y.as_f32(),
      emphasis_border_width: theme.emphasis_border_width.as_f32(),
      emphasis_border_paint_width: theme.emphasis_border_paint_width.as_f32(),
      box_padding_left: theme.box_padding_left.as_f32(),
      box_padding_right: theme.box_padding_right.as_f32(),
      box_padding_top: theme.box_padding_top.as_f32(),
      box_padding_bottom: theme.box_padding_bottom.as_f32(),
      highlight_pad_x: theme.highlight_pad_x.as_f32(),
      highlight_top_extra_fraction: theme.highlight_top_extra_fraction,
      highlight_bottom_extra_fraction: theme.highlight_bottom_extra_fraction,
      underline_fallback_top_from_baseline: theme.underline_fallback_top_from_baseline.as_f32(),
      underline_rule_thickness: theme.underline_rule_thickness.as_f32(),
      snap_underline_rules_to_pixels: theme.snap_underline_rules_to_pixels,
      double_underline_top_from_baseline: theme.double_underline_top_from_baseline.as_f32(),
      double_underline_gap: theme.double_underline_gap.as_f32(),
      highlight_spoken: theme.highlight_spoken.into(),
      highlight_insert: theme.highlight_insert.into(),
      highlight_alternative: theme.highlight_alternative.into(),
      pocket_color: theme.pocket_color.into(),
      hat_color: theme.hat_color.into(),
      block_color: theme.block_color.into(),
      tag_color: theme.tag_color.into(),
      analytic_color: theme.analytic_color.into(),
      undertag_color: theme.undertag_color.into(),
      cite_color: theme.cite_color.into(),
      underline_color: theme.underline_color.into(),
      emphasis_color: theme.emphasis_color.into(),
      condensed_color: theme.condensed_color.into(),
      ultracondensed_color: theme.ultracondensed_color.into(),
      normal_bold: theme.normal_bold,
      normal_italic: theme.normal_italic,
      normal_underline: theme.normal_underline.into(),
      pocket_bold: theme.pocket_bold,
      pocket_italic: theme.pocket_italic,
      pocket_underline: theme.pocket_underline.into(),
      hat_bold: theme.hat_bold,
      hat_italic: theme.hat_italic,
      hat_underline: theme.hat_underline.into(),
      block_bold: theme.block_bold,
      block_italic: theme.block_italic,
      block_underline: theme.block_underline.into(),
      tag_bold: theme.tag_bold,
      tag_italic: theme.tag_italic,
      tag_underline: theme.tag_underline.into(),
      analytic_bold: theme.analytic_bold,
      analytic_italic: theme.analytic_italic,
      analytic_underline: theme.analytic_underline.into(),
      undertag_bold: theme.undertag_bold,
      undertag_italic: theme.undertag_italic,
      undertag_underline: theme.undertag_underline.into(),
      cite_bold: theme.cite_bold,
      cite_italic: theme.cite_italic,
      cite_underline: theme.cite_underline.into(),
      underline_bold: theme.underline_bold,
      underline_italic: theme.underline_italic,
      underline_underline: theme.underline_underline.into(),
      emphasis_bold: theme.emphasis_bold,
      emphasis_italic: theme.emphasis_italic,
      emphasis_underline: theme.emphasis_underline.into(),
      condensed_bold: theme.condensed_bold,
      condensed_italic: theme.condensed_italic,
      condensed_underline: theme.condensed_underline.into(),
      ultracondensed_bold: theme.ultracondensed_bold,
      ultracondensed_italic: theme.ultracondensed_italic,
      ultracondensed_underline: theme.ultracondensed_underline.into(),
    }
  }
}

impl From<DocumentThemeSettings> for DocumentTheme {
  fn from(settings: DocumentThemeSettings) -> Self {
    Self {
      default_font_family: settings.default_font_family.into(),
      default_text_color: settings.default_text_color.into(),
      document_background_color: settings.document_background_color.into(),
      pageless_inset_x: px(settings.pageless_inset_x),
      pageless_inset_top: px(settings.pageless_inset_top),
      pageless_inset_bottom: px(settings.pageless_inset_bottom),
      body_font_size: px(settings.body_font_size),
      cite_font_size: px(settings.cite_font_size),
      condensed_font_size: px(settings.condensed_font_size),
      ultracondensed_font_size: px(settings.ultracondensed_font_size),
      pocket_font_size: px(settings.pocket_font_size),
      hat_font_size: px(settings.hat_font_size),
      block_font_size: px(settings.block_font_size),
      tag_font_size: px(settings.tag_font_size),
      undertag_font_size: px(settings.undertag_font_size),
      line_spacing: settings.line_spacing,
      line_gap_fraction: settings.line_gap_fraction,
      paragraph_after: px(settings.paragraph_after),
      pocket_before: px(settings.pocket_before),
      hat_before: px(settings.hat_before),
      block_before: px(settings.block_before),
      tag_before: px(settings.tag_before),
      pocket_border_width: px(settings.pocket_border_width),
      pocket_border_space_x: px(settings.pocket_border_space_x),
      pocket_border_space_y: px(settings.pocket_border_space_y),
      emphasis_border_width: px(settings.emphasis_border_width),
      emphasis_border_paint_width: px(settings.emphasis_border_paint_width),
      box_padding_left: px(settings.box_padding_left),
      box_padding_right: px(settings.box_padding_right),
      box_padding_top: px(settings.box_padding_top),
      box_padding_bottom: px(settings.box_padding_bottom),
      highlight_pad_x: px(settings.highlight_pad_x),
      highlight_top_extra_fraction: settings.highlight_top_extra_fraction,
      highlight_bottom_extra_fraction: settings.highlight_bottom_extra_fraction,
      underline_fallback_top_from_baseline: px(settings.underline_fallback_top_from_baseline),
      underline_rule_thickness: px(settings.underline_rule_thickness),
      snap_underline_rules_to_pixels: settings.snap_underline_rules_to_pixels,
      double_underline_top_from_baseline: px(settings.double_underline_top_from_baseline),
      double_underline_gap: px(settings.double_underline_gap),
      highlight_spoken: settings.highlight_spoken.into(),
      highlight_insert: settings.highlight_insert.into(),
      highlight_alternative: settings.highlight_alternative.into(),
      pocket_color: settings.pocket_color.into(),
      hat_color: settings.hat_color.into(),
      block_color: settings.block_color.into(),
      tag_color: settings.tag_color.into(),
      analytic_color: settings.analytic_color.into(),
      undertag_color: settings.undertag_color.into(),
      cite_color: settings.cite_color.into(),
      underline_color: settings.underline_color.into(),
      emphasis_color: settings.emphasis_color.into(),
      condensed_color: settings.condensed_color.into(),
      ultracondensed_color: settings.ultracondensed_color.into(),
      normal_bold: settings.normal_bold,
      normal_italic: settings.normal_italic,
      normal_underline: settings.normal_underline.into(),
      pocket_bold: settings.pocket_bold,
      pocket_italic: settings.pocket_italic,
      pocket_underline: settings.pocket_underline.into(),
      hat_bold: settings.hat_bold,
      hat_italic: settings.hat_italic,
      hat_underline: settings.hat_underline.into(),
      block_bold: settings.block_bold,
      block_italic: settings.block_italic,
      block_underline: settings.block_underline.into(),
      tag_bold: settings.tag_bold,
      tag_italic: settings.tag_italic,
      tag_underline: settings.tag_underline.into(),
      analytic_bold: settings.analytic_bold,
      analytic_italic: settings.analytic_italic,
      analytic_underline: settings.analytic_underline.into(),
      undertag_bold: settings.undertag_bold,
      undertag_italic: settings.undertag_italic,
      undertag_underline: settings.undertag_underline.into(),
      cite_bold: settings.cite_bold,
      cite_italic: settings.cite_italic,
      cite_underline: settings.cite_underline.into(),
      underline_bold: settings.underline_bold,
      underline_italic: settings.underline_italic,
      underline_underline: settings.underline_underline.into(),
      emphasis_bold: settings.emphasis_bold,
      emphasis_italic: settings.emphasis_italic,
      emphasis_underline: settings.emphasis_underline.into(),
      condensed_bold: settings.condensed_bold,
      condensed_italic: settings.condensed_italic,
      condensed_underline: settings.condensed_underline.into(),
      ultracondensed_bold: settings.ultracondensed_bold,
      ultracondensed_italic: settings.ultracondensed_italic,
      ultracondensed_underline: settings.ultracondensed_underline.into(),
    }
  }
}

impl From<Hsla> for StoredHsla {
  fn from(color: Hsla) -> Self {
    Self {
      h: color.h,
      s: color.s,
      l: color.l,
      a: color.a,
    }
  }
}

impl From<StoredHsla> for Hsla {
  fn from(color: StoredHsla) -> Self {
    Hsla {
      h: color.h,
      s: color.s,
      l: color.l,
      a: color.a,
    }
  }
}

impl From<ThemeUnderline> for ThemeUnderlineSetting {
  fn from(value: ThemeUnderline) -> Self {
    match value {
      ThemeUnderline::None => Self::None,
      ThemeUnderline::Single => Self::Single,
      ThemeUnderline::Double => Self::Double,
    }
  }
}

impl From<ThemeUnderlineSetting> for ThemeUnderline {
  fn from(value: ThemeUnderlineSetting) -> Self {
    match value {
      ThemeUnderlineSetting::None => Self::None,
      ThemeUnderlineSetting::Single => Self::Single,
      ThemeUnderlineSetting::Double => Self::Double,
    }
  }
}
