use serde_json::{Value, json};

use super::host_error;
use crate::bindings::flowstate::extension::host;

pub fn insert() -> Result<(), String> {
  let snapshot: Value = serde_json::from_str(&host::snapshot().map_err(host_error)?).map_err(|error| error.to_string())?;
  let generation = snapshot["generation"]
    .as_u64()
    .ok_or("missing generation")?;
  let end = snapshot["document"]["blocks"]
    .as_array()
    .ok_or("missing blocks")?
    .len();
  let mut random = [0_u8; 8];
  getrandom::fill(&mut random).map_err(|error| error.to_string())?;
  let asset_id = u64::from_le_bytes(random);
  let asset_wire_id = asset_id.to_string();
  let svg: &[u8] = br#"<svg xmlns="http://www.w3.org/2000/svg" width="80" height="30">
<rect width="80" height="30" fill="orange"/><text x="5" y="20">Wasm</text></svg>"#;
  let paragraph = json!({ "Paragraph": {
    "style": { "Custom": 1 }, "runs": [{ "text": "Styled extension paragraph", "styles": {
      "semantic": { "Custom": 2 }, "direct_underline": false,
      "strikethrough": true, "highlight": null
    }}]
  }});
  let equation = json!({ "Equation": {
    "source": "x^2 + y^2 = z^2", "syntax": "Latex", "display": "Display"
  }});
  let table = json!({ "Table": {
    "rows": [{ "cells": [
      { "blocks": [{ "Paragraph": plain_paragraph("A") }], "row_span": 1, "col_span": 1 },
      { "blocks": [{ "Paragraph": plain_paragraph("B") }], "row_span": 1, "col_span": 1 }
    ]}], "column_widths": ["Auto", "Auto"], "style": { "header_row": false }
  }});
  let image = json!({ "Image": {
    "asset_id": asset_wire_id, "alt_text": "Generated by the example extension",
    "caption": null, "sizing": "Intrinsic", "alignment": "Center"
  }});
  let request = json!({ "expected_generation": generation, "edits": [{
    "kind": "splice_blocks", "start": end, "end": end,
    "blocks": [paragraph, equation, table, image], "assets": [{
      "id": asset_wire_id, "mime_type": "image/svg+xml", "original_name": "wasm.svg",
      "content_hash": 0, "bytes": svg
    }]
  }]});
  host::apply_edits(&request.to_string()).map_err(host_error)?;
  Ok(())
}

fn plain_paragraph(text: &str) -> Value {
  json!({ "style": "Normal", "runs": [{ "text": text, "styles": {
    "semantic": "Plain", "direct_underline": false,
    "strikethrough": false, "highlight": null
  }}]})
}
