use serde::Deserialize;
use serde_json::{Value, json};

use super::host_error;
use crate::bindings::flowstate::extension::host;

#[derive(Deserialize)]
struct Snapshot {
    generation: u64,
    document: Document,
    selection: Selection,
}

#[derive(Deserialize)]
struct Document {
    blocks: Vec<Value>,
}

#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum Selection {
    Text { anchor: Offset, head: Offset },
    #[serde(other)]
    Other,
}

#[derive(Deserialize, serde::Serialize)]
struct Offset {
    paragraph: usize,
    byte: usize,
}

fn snapshot() -> Result<Snapshot, String> {
    let source = host::snapshot().map_err(host_error)?;
    serde_json::from_str(&source).map_err(|error| format!("invalid snapshot: {error}"))
}

pub fn inspect() -> Result<(), String> {
    let snapshot = host::snapshot().map_err(host_error)?;
    let selection = host::selection().map_err(host_error)?;
    host::set_status(&format!("snapshot={} bytes; selection={selection}", snapshot.len()));
    host::set_action_label("inspect", "Inspect again").map_err(host_error)
}

pub fn replace_selection() -> Result<(), String> {
    let snapshot = snapshot()?;
    let Selection::Text { anchor, head } = snapshot.selection else {
        return Err("select text before running this action".into());
    };
    let request = json!({
        "expected_generation": snapshot.generation,
        "edits": [{
            "kind": "replace_text",
            "start": anchor,
            "end": head,
            "fragment": styled_fragment("Replaced by the example extension"),
        }],
    });
    host::apply_edits(&request.to_string()).map_err(host_error)?;
    Ok(())
}

fn styled_fragment(text: &str) -> Value {
    json!({
        "format": "gpui-flowtext.rich-text-fragment.v1",
        "paragraphs": [{
            "style": "Normal",
            "runs": [{ "text": text, "styles": {
                "semantic": { "Custom": 1 }, "direct_underline": true,
                "strikethrough": false, "highlight": { "Custom": 1 }
            }}]
        }],
        "blocks": [], "assets": []
    })
}

pub fn refresh() -> Result<(), String> {
    host::refresh_from_disk().map_err(host_error)?;
    Ok(())
}

pub fn insert_blocks() -> Result<(), String> {
    let snapshot = snapshot()?;
    let mut random = [0_u8; 8];
    getrandom::fill(&mut random).map_err(|error| error.to_string())?;
    let asset_id = u64::from_le_bytes(random);
    let svg = br#"<svg xmlns="http://www.w3.org/2000/svg" width="80" height="30">
<rect width="80" height="30" fill="orange"/><text x="5" y="20">Wasm</text></svg>"#;
    let paragraph = json!({ "Paragraph": {
        "style": { "Custom": 1 },
        "runs": [{ "text": "Styled extension paragraph", "styles": {
            "semantic": { "Custom": 2 }, "direct_underline": false,
            "strikethrough": true, "highlight": null
        }}]
    }});
    let equation = json!({ "Equation": {
        "source": "x^2 + y^2 = z^2", "syntax": "Latex", "display": "Display"
    }});
    let table = json!({ "Table": {
        "rows": [{ "cells": [
            { "blocks": [{ "Paragraph": plain_paragraph("A") }], "row_span": 1, "col_span": 1 },
            { "blocks": [{ "Paragraph": plain_paragraph("B") }], "row_span": 1, "col_span": 1 }
        ]}],
        "column_widths": ["Auto", "Auto"], "style": { "header_row": false }
    }});
    let image = json!({ "Image": {
        "asset_id": asset_id, "alt_text": "Generated by the example extension",
        "caption": null, "sizing": "Intrinsic", "alignment": "Center"
    }});
    let request = json!({
        "expected_generation": snapshot.generation,
        "edits": [{
            "kind": "splice_blocks",
            "start": snapshot.document.blocks.len(), "end": snapshot.document.blocks.len(),
            "blocks": [paragraph, equation, table, image],
            "assets": [{
                "id": asset_id, "mime_type": "image/svg+xml", "original_name": "wasm.svg",
                "content_hash": asset_id, "bytes": svg
            }]
        }]
    });
    host::apply_edits(&request.to_string()).map_err(host_error)?;
    Ok(())
}

fn plain_paragraph(text: &str) -> Value {
    json!({
        "style": "Normal",
        "runs": [{ "text": text, "styles": {
            "semantic": "Plain", "direct_underline": false,
            "strikethrough": false, "highlight": null
        }}]
    })
}
